String SPLASH_SCREEN = '/SplashScreen',
    INTROSLIDER = '/IntroductionScreen',
    LOGIN_SCREEN = '/LoginScreen',
    REGISTRATION_SCREEN = '/RegistrationScreen',
    PHONENUMBER = '/MobilePhoneState',
    RESETPASSWORD = '/ResetPassword',
    OTPSCREEN = '/OTPScreen',
    HOMEPAGE = '/HomePage',
    DEMO = '/demo';
